[theme]
base = "light"
primaryColor = "#D32F2F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
